// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: atomix/multiraft/atomic/map/v1/config.proto

package v1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AtomicMapConfig struct {
	Cache CacheConfig `protobuf:"bytes,1,opt,name=cache,proto3" json:"cache"`
}

func (m *AtomicMapConfig) Reset()         { *m = AtomicMapConfig{} }
func (m *AtomicMapConfig) String() string { return proto.CompactTextString(m) }
func (*AtomicMapConfig) ProtoMessage()    {}
func (*AtomicMapConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_614845aa33136d63, []int{0}
}
func (m *AtomicMapConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AtomicMapConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AtomicMapConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AtomicMapConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AtomicMapConfig.Merge(m, src)
}
func (m *AtomicMapConfig) XXX_Size() int {
	return m.Size()
}
func (m *AtomicMapConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AtomicMapConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AtomicMapConfig proto.InternalMessageInfo

func (m *AtomicMapConfig) GetCache() CacheConfig {
	if m != nil {
		return m.Cache
	}
	return CacheConfig{}
}

type CacheConfig struct {
	Enabled          bool           `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Size_            uint64         `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	EvictAfter       *time.Duration `protobuf:"bytes,3,opt,name=evict_after,json=evictAfter,proto3,stdduration" json:"evict_after,omitempty"`
	EvictionInterval *time.Duration `protobuf:"bytes,4,opt,name=eviction_interval,json=evictionInterval,proto3,stdduration" json:"eviction_interval,omitempty"`
}

func (m *CacheConfig) Reset()         { *m = CacheConfig{} }
func (m *CacheConfig) String() string { return proto.CompactTextString(m) }
func (*CacheConfig) ProtoMessage()    {}
func (*CacheConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_614845aa33136d63, []int{1}
}
func (m *CacheConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CacheConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CacheConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CacheConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheConfig.Merge(m, src)
}
func (m *CacheConfig) XXX_Size() int {
	return m.Size()
}
func (m *CacheConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CacheConfig proto.InternalMessageInfo

func (m *CacheConfig) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *CacheConfig) GetSize_() uint64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *CacheConfig) GetEvictAfter() *time.Duration {
	if m != nil {
		return m.EvictAfter
	}
	return nil
}

func (m *CacheConfig) GetEvictionInterval() *time.Duration {
	if m != nil {
		return m.EvictionInterval
	}
	return nil
}

func init() {
	proto.RegisterType((*AtomicMapConfig)(nil), "atomix.multiraft.atomic.map.v1.AtomicMapConfig")
	proto.RegisterType((*CacheConfig)(nil), "atomix.multiraft.atomic.map.v1.CacheConfig")
}

func init() {
	proto.RegisterFile("atomix/multiraft/atomic/map/v1/config.proto", fileDescriptor_614845aa33136d63)
}

var fileDescriptor_614845aa33136d63 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x63, 0x08, 0x3f, 0x72, 0x06, 0xc0, 0x62, 0x30, 0x1d, 0xdc, 0xaa, 0x53, 0xa5, 0x4a,
	0xb6, 0x0a, 0x2f, 0x40, 0x53, 0x24, 0x84, 0x04, 0x4b, 0x46, 0x96, 0xca, 0x49, 0x9d, 0x60, 0x29,
	0x89, 0xa3, 0xe0, 0x44, 0x88, 0xa7, 0x60, 0xe4, 0x91, 0x2a, 0xb1, 0x74, 0x64, 0x02, 0x94, 0xbc,
	0x08, 0x8a, 0xdd, 0x20, 0x26, 0xc4, 0x76, 0xee, 0xf5, 0xf9, 0xce, 0xf5, 0x81, 0x53, 0xae, 0x55,
	0x26, 0x9f, 0x58, 0x56, 0xa5, 0x5a, 0x96, 0x3c, 0xd6, 0xcc, 0x2c, 0x22, 0x96, 0xf1, 0x82, 0xd5,
	0x33, 0x16, 0xa9, 0x3c, 0x96, 0x09, 0x2d, 0x4a, 0xa5, 0x15, 0x22, 0xd6, 0x4c, 0x7f, 0xcc, 0xd4,
	0x9a, 0x69, 0xc6, 0x0b, 0x5a, 0xcf, 0x06, 0x24, 0x51, 0x2a, 0x49, 0x05, 0x33, 0xee, 0xb0, 0x8a,
	0xd9, 0xaa, 0x2a, 0xb9, 0x96, 0x2a, 0xb7, 0xfc, 0xe0, 0x34, 0x51, 0x89, 0x32, 0x92, 0x75, 0xca,
	0x6e, 0xc7, 0xf7, 0xf0, 0x68, 0x6e, 0x62, 0xee, 0x78, 0xb1, 0x30, 0xe7, 0xd0, 0x35, 0xdc, 0x8b,
	0x78, 0xf4, 0x20, 0x30, 0x18, 0x81, 0x89, 0x77, 0x3e, 0xa5, 0x7f, 0x1f, 0xa6, 0x8b, 0xce, 0x6c,
	0x59, 0xdf, 0x5d, 0x7f, 0x0c, 0x9d, 0xc0, 0xf2, 0xe3, 0x37, 0x00, 0xbd, 0x5f, 0x8f, 0x08, 0xc3,
	0x03, 0x91, 0xf3, 0x30, 0x15, 0x2b, 0x13, 0x7d, 0x18, 0xf4, 0x23, 0x42, 0xd0, 0x7d, 0x94, 0xcf,
	0x02, 0xef, 0x8c, 0xc0, 0xc4, 0x0d, 0x8c, 0x46, 0x97, 0xd0, 0x13, 0xb5, 0x8c, 0xf4, 0x92, 0xc7,
	0x5a, 0x94, 0x78, 0xd7, 0x7c, 0xe6, 0x8c, 0xda, 0x96, 0xb4, 0x6f, 0x49, 0xaf, 0xb6, 0x2d, 0x7d,
	0xf7, 0xf5, 0x73, 0x08, 0x02, 0x68, 0x98, 0x79, 0x87, 0xa0, 0x5b, 0x78, 0x62, 0x26, 0xa9, 0xf2,
	0xa5, 0xcc, 0xb5, 0x28, 0x6b, 0x9e, 0x62, 0xf7, 0x7f, 0x39, 0xc7, 0x3d, 0x79, 0xb3, 0x05, 0x7d,
	0xbc, 0x6e, 0x08, 0xd8, 0x34, 0x04, 0x7c, 0x35, 0x04, 0xbc, 0xb4, 0xc4, 0xd9, 0xb4, 0xc4, 0x79,
	0x6f, 0x89, 0x13, 0xee, 0x9b, 0x90, 0x8b, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xe9, 0xab,
	0x20, 0xcf, 0x01, 0x00, 0x00,
}

func (m *AtomicMapConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AtomicMapConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AtomicMapConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Cache.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintConfig(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *CacheConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CacheConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CacheConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EvictionInterval != nil {
		n2, err2 := github_com_gogo_protobuf_types.StdDurationMarshalTo(*m.EvictionInterval, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(*m.EvictionInterval):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintConfig(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x22
	}
	if m.EvictAfter != nil {
		n3, err3 := github_com_gogo_protobuf_types.StdDurationMarshalTo(*m.EvictAfter, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(*m.EvictAfter):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintConfig(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x1a
	}
	if m.Size_ != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.Size_))
		i--
		dAtA[i] = 0x10
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AtomicMapConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Cache.Size()
	n += 1 + l + sovConfig(uint64(l))
	return n
}

func (m *CacheConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	if m.Size_ != 0 {
		n += 1 + sovConfig(uint64(m.Size_))
	}
	if m.EvictAfter != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdDuration(*m.EvictAfter)
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.EvictionInterval != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdDuration(*m.EvictionInterval)
		n += 1 + l + sovConfig(uint64(l))
	}
	return n
}

func sovConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AtomicMapConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AtomicMapConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AtomicMapConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cache", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Cache.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CacheConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CacheConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CacheConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvictAfter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EvictAfter == nil {
				m.EvictAfter = new(time.Duration)
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(m.EvictAfter, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvictionInterval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EvictionInterval == nil {
				m.EvictionInterval = new(time.Duration)
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(m.EvictionInterval, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
